/// Why a popup produced its final outcome.
enum PopupDismissReason {
  completed,
  manual,
  timeout,
  externalEvent,
  barrier,
  drag,
  back,
  routeChanged,
  replaced,
  toggled,
  anchorDetached,
  parentDismissed,
  hostDetached,
  hostUnavailable,
  rendererUnavailable,
  queueOverflow,
  runtimeDisposed,
}
