/// 弹窗产生最终业务结果的原因（与退出动画无关）。
enum PopupDismissReason {
  completed,
  manual,
  timeout,
  externalEvent,
  barrier,
  drag,
  back,
  routeChanged,
  replaced,
  toggled,
  anchorDetached,
  parentDismissed,
  hostDetached,
  hostUnavailable,
  rendererUnavailable,
  queueOverflow,
  runtimeDisposed,
}
